Added German version of the games man page
suve/LD25 pull request #3
Opened 2017-09-29 15:17 UTC by kwinzig

Resolving issue #1

2017-09-29 15:26 UTC, ghost reviewed
Can you translate the titles as well?
NAME, SYNOPSIS, DESCRIPTION, CONTROLS, DIRECTORIES and AUTHOR

2017-09-29 15:40 UTC, kwinzig commented
Sure :) I'm sorry.  I must have overlooked to translate these.

2017-10-01 06:08 UTC, suve requested changes
Apart from those minor issues, looks good!

2017-10-01 06:08 UTC, suve commented on pkg/colorful-german.man
> +.TH man 6 "2014-03-16" "1.2" "Games Manual"
"Games Manual" should also be translated.

2017-10-01 06:08 UTC, suve commented on pkg/colorful-german.man
> +\fBArrow keys\fR
"Arrow keys" should also be translated.

2017-10-02 17:19 UTC, suve approved these changes

2017-10-02 17:20 UTC, merged

2017-10-02 17:21 UTC, suve commented
Seems fine now, merged. Thanks!