Add dutch translation
suve/LD25 pull request #5
Opened 2017-10-01 10:40 UTC by TomG777

2017-10-02 17:11 UTC, suve requested changes

2017-10-02 17:11 UTC, suve commented on pkg/colorful-dutch.man
> +.SH DIRECTORIES
Is it also "directories" in Dutch, or is this not translated?

2017-10-02 20:20 UTC, TomG777 commented
Directories is a correct Dutch translation that comes closest. A possible other translation could be "mappen" which translates closer to "folders". Both could be used, but "mappen" is less formal.

2017-10-03 19:09 UTC, suve approved these changes

2017-10-03 19:11 UTC, merged

2017-10-03 19:12 UTC, suve commented
All-righty, then. Merged. Thanks!